export default {
  'sample.systembackdrops.types-header': '背景类型',
  'sample.systembackdrops.mica-header': 'MicaController',
  'sample.systembackdrops.acrylic-header': 'DesktopAcrylicController',
  'sample.systembackdrops.show-window': '显示窗口',
  'sample.systembackdrops.types-intro': '窗口可以使用以下系统背景：',
  'sample.systembackdrops.mica-name': '1. 云母',
  'sample.systembackdrops.mica-description': ' — 不透明材质，仅采样一次桌面壁纸，为窗口背景着色。最适合应用的主窗口。',
  'sample.systembackdrops.mica-alt-name': '2. 云母替代',
  'sample.systembackdrops.mica-alt-description': ' — 云母的变体，着色更浓。推荐用于标题栏中带有选项卡的应用。',
  'sample.systembackdrops.acrylic-name': '3. 桌面亚克力（基本）',
  'sample.systembackdrops.acrylic-description': ' — 半透明材质，模糊显示窗口后方的内容。',
  'sample.systembackdrops.acrylic-thin-name': '4. 桌面亚克力（薄）',
  'sample.systembackdrops.acrylic-thin-description': ' — 更轻薄、透明度更高的桌面亚克力变体。',
  'sample.systembackdrops.comparison-title': '云母与亚克力：',
  'sample.systembackdrops.comparison-description': ' 云母是不透明的，在窗口背景中呈现桌面壁纸。桌面亚克力是半透明的，会实时显示窗口后方内容的模糊视图。云母仅捕获一次壁纸，性能更好；亚克力则持续更新。',
  'sample.systembackdrops.api-intro': 'API 中有三种背景类型：',
  'sample.systembackdrops.api-system-name': '• SystemBackdrop',
  'sample.systembackdrops.api-system-description': ' — 所有背景类型的基类。',
  'sample.systembackdrops.api-mica-name': '• MicaBackdrop',
  'sample.systembackdrops.api-mica-description': ' — 应用云母材质。设置 Kind 属性可切换基本和替代类型。',
  'sample.systembackdrops.api-acrylic-name': '• DesktopAcrylicBackdrop',
  'sample.systembackdrops.api-acrylic-description': ' — 应用桌面亚克力材质（仅基本类型）。',
  'sample.systembackdrops.requirements': '所有云母变体均要求 Windows 11 版本 22000 或更高版本。应用内亚克力（AcrylicBrush）是用于 UI 元素内部的独立 XAML 画笔，不属于窗口背景。',
  'sample.systembackdrops.mica-controller-description': 'MicaController 提供可自定义的云母材质应用方式。可以修改 FallbackColor、Kind、LuminosityOpacity、TintColor 和 TintOpacity。',
  'sample.systembackdrops.mica-kinds-intro': '云母有两种类型：',
  'sample.systembackdrops.mica-base-name': '1. 基本',
  'sample.systembackdrops.mica-base-description': ' — 默认的较浅外观。',
  'sample.systembackdrops.mica-controller-alt-name': '2. 替代',
  'sample.systembackdrops.mica-controller-alt-description': ' — 更深的外观，桌面壁纸着色更浓。',
  'sample.systembackdrops.acrylic-controller-description': 'DesktopAcrylicController 提供可自定义的桌面亚克力材质应用方式。它支持与 MicaController 相同的自定义属性。',
  'sample.systembackdrops.acrylic-kinds-intro': '桌面亚克力有两种类型：',
  'sample.systembackdrops.acrylic-base-name': '1. 基本',
  'sample.systembackdrops.acrylic-base-description': ' — 默认的较深外观，透明度较低。',
  'sample.systembackdrops.acrylic-controller-thin-name': '2. 薄',
  'sample.systembackdrops.acrylic-controller-thin-description': ' — 更浅的外观，透明度更高。',
  'sample.systembackdrops.acrylic-controller-note': '注意：DesktopAcrylicBackdrop 始终使用基本类型。若要使用薄类型，必须直接使用 DesktopAcrylicController。',
  'sample.systembackdrops.window-title': '系统背景示例窗口',
  'sample.systembackdrops.current-backdrop': '当前背景',
  'sample.systembackdrops.window-theme': '窗口主题',
  'sample.systembackdrops.backdrop.mica': '云母',
  'sample.systembackdrops.backdrop.mica-alt': '云母替代',
  'sample.systembackdrops.backdrop.acrylic': '亚克力',
  'sample.systembackdrops.backdrop.acrylic-thin': '薄亚克力',
  'sample.systembackdrops.backdrop.none': '无',
  'sample.systembackdrops.theme.default': '使用系统设置',
  'sample.systembackdrops.theme.light': '浅色',
  'sample.systembackdrops.theme.dark': '深色',
  'sample.systembackdrops.window-opened': '窗口已打开。',
  'sample.systembackdrops.popup-blocked': '浏览器阻止了示例窗口。请允许此站点打开弹出窗口，然后重试。',
  'sample.systembackdrops.window-unavailable': '窗口宿主不可用。',
  'sample.systembackdrops.window-failed': '无法打开示例窗口。',
  'sample.systembackdrops.window-recovery-failed': '桌面宿主无法重新连接此示例窗口。请保持窗口打开，并在宿主可用后重试。',
  'sample.systembackdrops.retry-connection': '重新连接',
  'sample.systembackdrops.native-unavailable': '普通浏览器无法显示系统背景，请在支持系统背景的桌面宿主中查看。',
  'sample.systembackdrops.high-contrast': '已启用高对比度。窗口使用系统回退颜色。',
  'sample.systembackdrops.inactive': '窗口未激活。窗口使用回退颜色。',
  'sample.systembackdrops.transparency-disabled': '已禁用透明效果。窗口使用回退颜色。',
  'sample.systembackdrops.energy-saver': '已启用节能模式。窗口使用回退颜色。',
  'sample.systembackdrops.mica-trying-acrylic': '当前宿主不支持云母，正在尝试亚克力。',
  'sample.systembackdrops.mica-alt-trying-acrylic': '当前宿主不支持云母替代，正在尝试亚克力。',
  'sample.systembackdrops.acrylic-base-default': '当前宿主不支持基本亚克力，已切换为默认颜色。',
  'sample.systembackdrops.acrylic-thin-default': '当前宿主不支持薄亚克力，已切换为默认颜色。',
  'sample.systembackdrops.effect-unavailable': '当前宿主不支持所请求的背景。窗口使用回退颜色。',
  'sample.systembackdrops.applied': '背景已更改为{backdrop}。',
  'sample.systembackdrops.closed': '窗口已关闭。',
  'sample.systembackdrops.operation-failed': '无法更改背景或主题。'
};
