export default {
  "text.titlebar": "标题栏",
  "sample.titlebar.customization-intro": "若要不使用 TitleBar 控件来完整自定义标题栏，请参阅 ",
  "sample.titlebar.app-window-title-bar": "AppWindowTitleBar",
  "sample.titlebar.sample-suffix": " 示例。",
  "sample.titlebar.configuration-header": "TitleBar 配置",
  "sample.titlebar.drag-header": "TitleBar 拖动区域",
  "sample.titlebar.end-to-end-header": "完整的 TitleBar 示例",
  "sample.titlebar.search": "搜索…",
  "sample.titlebar.title-option": "标题",
  "sample.titlebar.subtitle-option": "副标题",
  "sample.titlebar.default-title": "WinUI 示例库",
  "sample.titlebar.default-subtitle": "预览版",
  "sample.titlebar.back-button-option": "返回按钮可见",
  "sample.titlebar.pane-toggle-option": "导航窗格切换按钮可见",
  "sample.titlebar.drag-description": "拖动区域只能在真实窗口中查看。点击下方按钮打开示例窗口，即可切换状态徽章的 TitleBar.IsDragRegion，并在动态内容更改后调用 RecomputeDragRegions()。",
  "sample.titlebar.end-to-end-description": "点击下方按钮，在新窗口中查看完整的 TitleBar 示例，并将其部分属性绑定到 NavigationView 和导航框架。",
  "sample.titlebar.configuration-output": "标题：{title}\n副标题：{subtitle}\n返回按钮：{back}\n导航窗格切换：{pane}",
  "sample.titlebar.visible": "可见",
  "sample.titlebar.collapsed": "收起",
  "sample.titlebar.drag-window-title": "TitleBar 拖动区域示例",
  "sample.titlebar.end-window-title": "TitleBar 示例窗口",
  "sample.titlebar.browser-host-unavailable": "示例窗口已打开。普通浏览器不支持原生窗口拖动区域或系统背景，请在支持这些功能的桌面宿主中查看。",
  "sample.titlebar.drag-title": "拖动区域",
  "sample.titlebar.drag-subtitle": "尝试拖动窗口",
  "sample.titlebar.status-badge": "状态",
  "sample.titlebar.custom-drag-title": "自定义拖动区域",
  "sample.titlebar.drag-guidance": "尝试从标题栏的不同位置拖动窗口。Windows App SDK 2.1 的新默认行为会自动将交互控件（如搜索框）排除在拖动区域之外。",
  "sample.titlebar.badge-heading": "状态徽章：TitleBar.IsDragRegion",
  "sample.titlebar.badge-guidance": "为标题栏中的徽章选择一个值。",
  "sample.titlebar.badge-unset": "未设置（由框架决定；按钮为交互控件，因此可点击）",
  "sample.titlebar.badge-true": "True（始终可拖动；覆盖框架默认行为）",
  "sample.titlebar.badge-false": "False（始终可点击）",
  "sample.titlebar.dynamic-heading": "动态内容",
  "sample.titlebar.dynamic-guidance": "在运行时添加或移除 TitleBar.Content 中的元素后，调用 RecomputeDragRegions() 刷新拖动区域。",
  "sample.titlebar.toggle-extra": "切换额外的标题栏按钮",
  "sample.titlebar.recompute": "RecomputeDragRegions()",
  "sample.titlebar.badge-clicked": "已点击状态徽章",
  "sample.titlebar.extra": "额外按钮",
  "sample.titlebar.extra-added": "已在 TitleBar.Content 中添加按钮。请调用 RecomputeDragRegions() 刷新拖动区域。",
  "sample.titlebar.extra-removed": "已移除按钮。请调用 RecomputeDragRegions() 刷新拖动区域。",
  "sample.titlebar.recomputed": "已调用 RecomputeDragRegions()。",
  "sample.titlebar.end-subtitle": "TitleBar 示例",
  "sample.titlebar.menu-item": "菜单项{index}",
  "sample.titlebar.sample-page": "示例页 {index}",
  "sample.titlebar.page1-body": "示例内容",
  "sample.titlebar.nav-output": "页面 {index}，导航历史记录：{count}"
};
