export default {
  'catalog.group.windowing': 'Windowing',
  'catalog.item.createmultiplewindows.title': 'Multiple windows',
  'catalog.item.createmultiplewindows.subtitle': 'An example showing the creation of single-threaded top level Xaml windows.',
  'catalog.item.titlebar.title': 'TitleBar',
  'catalog.item.titlebar.subtitle': 'An example showing how to use the default TitleBar control.',
  "catalog.home.title": "WinUI on Web Gallery",
  "catalog.home.version": "1.0.0-Insider",
  "catalog.home.recent": "Recent",
  "catalog.home.favorites": "Favorites",
  "catalog.home.recently-visited": "Recently visited",
  "catalog.home.recently-updated": "Recently added or updated",
  "catalog.home.no-favorites": "No favorites yet",
  "catalog.home.favorites-description": "Favorite samples by clicking the star icon on the sample page.",
  "catalog.home.scroll-left": "Scroll left",
  "catalog.home.scroll-right": "Scroll right",
  "catalog.home.sample-count": "{count} samples",
  "catalog.home.tile.getting-started.title": "Getting started",
  "catalog.home.tile.getting-started.description": "Get started with WinUI and explore detailed documentation.",
  "catalog.home.tile.design.title": "Design",
  "catalog.home.tile.design.description": "Guidelines and toolkits for creating stunning WinUI experiences.",
  "catalog.home.tile.github.title": "WinUI on Web on GitHub",
  "catalog.home.tile.github.description": "Explore the WinUI on Web source code and repository.",
  "catalog.home.tile.toolkit.title": "Community Toolkit",
  "catalog.home.tile.toolkit.description": "A collection of helper functions, controls, and app services.",
  "catalog.home.tile.samples.title": "Code samples",
  "catalog.home.tile.samples.description": "Find samples that demonstrate specific tasks, features, and APIs.",
  "catalog.home.tile.store.title": "Partner Center",
  "catalog.home.tile.store.description": "Upload your app to the Store.",
  "catalog.group.buttons": "Basic input",
  "catalog.group.collections": "Collections",
  "catalog.group.dateandtime": "Date & time",
  "catalog.group.dialogsandflyouts": "Dialogs & flyouts",
  "catalog.group.layout": "Layout",
  "catalog.group.media": "Media",
  "catalog.group.menusandtoolbars": "Menus & toolbars",
  "catalog.group.motion": "Motion",
  "catalog.item.pagetransition.title": "Page Transitions",
  "catalog.item.pagetransition.subtitle": "Page transitions provide visual feedback about the relationship between pages.",
  "catalog.group.navigation": "Navigation",
  "catalog.group.scrolling": "Scrolling",
  "catalog.group.statusandinfo": "Status & info",
  "catalog.group.styles": "Styles",
  "catalog.group.text": "Text",
  "catalog.item.button.title": "Button",
  "catalog.item.button.subtitle": "A control that responds to user input and raises a Click event.",
  "catalog.item.checkbox.title": "CheckBox",
  "catalog.item.checkbox.subtitle": "A control that a user can select or clear.",
  "catalog.item.colorpicker.title": "ColorPicker",
  "catalog.item.colorpicker.subtitle": "A control that displays a selectable color spectrum.",
  "catalog.item.combobox.title": "ComboBox",
  "catalog.item.combobox.subtitle": "A drop-down list of items a user can select from.",
  "catalog.item.dropdownbutton.title": "DropDownButton",
  "catalog.item.dropdownbutton.subtitle": "A button that displays a flyout of choices when clicked.",
  "catalog.item.hyperlinkbutton.title": "HyperlinkButton",
  "catalog.item.hyperlinkbutton.subtitle": "A button that appears as hyperlink text, and can navigate to a URI or handle a Click event.",
  "catalog.item.radiobutton.title": "RadioButton",
  "catalog.item.radiobutton.subtitle": "A control that allows a user to select a single option from a group of options.",
  "catalog.item.rating.title": "RatingControl",
  "catalog.item.rating.subtitle": "Rate something 1 to 5 stars.",
  "catalog.item.repeatbutton.title": "RepeatButton",
  "catalog.item.repeatbutton.subtitle": "A button that raises its Click event repeatedly from the time it's pressed until it's released.",
  "catalog.item.slider.title": "Slider",
  "catalog.item.slider.subtitle": "A control that lets the user select from a range of values by moving a Thumb control along a track.",
  "catalog.item.splitbutton.title": "SplitButton",
  "catalog.item.splitbutton.subtitle": "A two-part button that displays a flyout when its secondary part is clicked.",
  "catalog.item.togglebutton.title": "ToggleButton",
  "catalog.item.togglebutton.subtitle": "A button that can be switched between two states like a CheckBox.",
  "catalog.item.togglesplitbutton.title": "ToggleSplitButton",
  "catalog.item.togglesplitbutton.subtitle": "A version of the SplitButton where the activation target toggles on/off.",
  "catalog.item.toggleswitch.title": "ToggleSwitch",
  "catalog.item.toggleswitch.subtitle": "A switch that can be toggled between 2 states.",
  "catalog.item.flipview.title": "FlipView",
  "catalog.item.flipview.subtitle": "Presents a collection of items that the user can flip through, one item at a time.",
  "catalog.item.gridview.title": "GridView",
  "catalog.item.gridview.subtitle": "A control that presents a collection of items in rows and columns.",
  "catalog.item.itemsrepeater.title": "ItemsRepeater",
  "catalog.item.itemsrepeater.subtitle": "A flexible, primitive control for data-driven layouts.",
  "catalog.item.itemsview.title": "ItemsView",
  "catalog.item.itemsview.subtitle": "A control that presents a collection of items using various layouts.",
  "catalog.item.listview.title": "ListView",
  "catalog.item.listview.subtitle": "A control that presents a collection of items in a vertical list.",
  "catalog.item.pulltorefresh.title": "PullToRefresh",
  "catalog.item.pulltorefresh.subtitle": "Provides the ability to pull on a collection of items in a list/grid to refresh the contents of the collection.",
  "catalog.item.treeview.title": "TreeView",
  "catalog.item.treeview.subtitle": "The  TreeView control is a hierarchical list pattern with expanding and collapsing nodes that contain nested items.",
  "catalog.item.calendardatepicker.title": "CalendarDatePicker",
  "catalog.item.calendardatepicker.subtitle": "A control that lets users pick a date value using a calendar.",
  "catalog.item.calendarview.title": "CalendarView",
  "catalog.item.calendarview.subtitle": "A control that presents a calendar for a user to choose a date from.",
  "catalog.item.datepicker.title": "DatePicker",
  "catalog.item.datepicker.subtitle": "A control that lets a user pick a date value.",
  "catalog.item.timepicker.title": "TimePicker",
  "catalog.item.timepicker.subtitle": "A configurable control that lets a user pick a time value.",
  "catalog.item.contentdialog.title": "ContentDialog",
  "catalog.item.contentdialog.subtitle": "A dialog box that can be customized to contain any XAML content.",
  "catalog.item.flyout.title": "Flyout",
  "catalog.item.flyout.subtitle": "Shows contextual information and enables user interaction.",
  "catalog.item.popup.title": "Popup",
  "catalog.item.popup.subtitle": "A UI element displaying temporary content over existing interface.",
  "catalog.item.teachingtip.title": "TeachingTip",
  "catalog.item.teachingtip.subtitle": "A content-rich flyout for guiding users and enabling teaching moments.",
  "catalog.item.border.title": "Border",
  "catalog.item.border.subtitle": "A container control that draws a boundary line, background, or both, around another object.",
  "catalog.item.canvas.title": "Canvas",
  "catalog.item.canvas.subtitle": "A layout panel that supports absolute positioning of child elements relative to the top left corner of the canvas.",
  "catalog.item.expander.title": "Expander",
  "catalog.item.expander.subtitle": "A container with a header that can be expanded to show a body with more content.",
  "catalog.item.grid.title": "Grid",
  "catalog.item.grid.subtitle": "A layout panel that supports arranging child elements in rows and columns.",
  "catalog.item.relativepanel.title": "RelativePanel",
  "catalog.item.relativepanel.subtitle": "A panel that uses relationships between elements to define layout.",
  "catalog.item.splitview.title": "SplitView",
  "catalog.item.splitview.subtitle": "A container that has 2 content areas, with multiple display options for the pane.",
  "catalog.item.stackpanel.title": "StackPanel",
  "catalog.item.stackpanel.subtitle": "A layout panel that arranges child elements into a single line that can be oriented horizontally or vertically.",
  "catalog.item.variablesizedwrapgrid.title": "VariableSizedWrapGrid",
  "catalog.item.variablesizedwrapgrid.subtitle": "A layout panel that supports arranging child elements in rows and columns. Each child element can span multiple rows and columns.",
  "catalog.item.viewbox.title": "Viewbox",
  "catalog.item.viewbox.subtitle": "A container control that scales its content to a specified size.",
  "catalog.item.captureelement.title": "Capture Element / Camera Preview",
  "catalog.item.captureelement.subtitle": "A sample for doing a camera preview.",
  "catalog.item.image.title": "Image",
  "catalog.item.image.subtitle": "A control to display image content.",
  "catalog.item.mediaplayerelement.title": "MediaPlayerElement",
  "catalog.item.mediaplayerelement.subtitle": "A control to display video and image content.",
  "catalog.item.personpicture.title": "PersonPicture",
  "catalog.item.personpicture.subtitle": "Displays the picture of a person/contact.",
  "catalog.item.appbarbutton.title": "AppBarButton",
  "catalog.item.appbarbutton.subtitle": "A button that's styled for use in a CommandBar.",
  "catalog.item.appbarseparator.title": "AppBarSeparator",
  "catalog.item.appbarseparator.subtitle": "A vertical line that's used to visually separate groups of commands in an app bar.",
  "catalog.item.toggleappbarbutton.title": "AppBarToggleButton",
  "catalog.item.toggleappbarbutton.subtitle": "A button that can be on, off, or indeterminate like a CheckBox, and is styled for use in an app bar or other specialized UI.",
  "catalog.item.commandbar.title": "CommandBar",
  "catalog.item.commandbar.subtitle": "A toolbar for displaying application-specific commands that handles layout and resizing of its contents.",
  "catalog.item.commandbarflyout.title": "CommandBarFlyout",
  "catalog.item.commandbarflyout.subtitle": "A mini-toolbar displaying proactive commands, and an optional menu of commands.",
  "catalog.item.menubar.title": "MenuBar",
  "catalog.item.menubar.subtitle": "A classic menu, allowing the display of MenuItems containing MenuFlyoutItems.",
  "catalog.item.menuflyout.title": "MenuFlyout",
  "catalog.item.menuflyout.subtitle": "Shows a contextual list of simple commands or options.",
  "catalog.item.standarduicommand.title": "StandardUICommand",
  "catalog.item.standarduicommand.subtitle": "A StandardUICommand is a built-in 'XamlUICommand' which represents a commonly used command, e.g. 'Save'.",
  "catalog.item.swipecontrol.title": "SwipeControl",
  "catalog.item.swipecontrol.subtitle": "Touch gesture for quick menu actions on items.",
  "catalog.item.xamluicommand.title": "XamlUICommand",
  "catalog.item.xamluicommand.subtitle": "An object which is used to define the look and feel of a given command.",
  "catalog.item.parallaxview.title": "ParallaxView",
  "catalog.item.parallaxview.subtitle": "A container control that provides the parallax effect when scrolling.",
  "catalog.item.breadcrumbbar.title": "BreadcrumbBar",
  "catalog.item.breadcrumbbar.subtitle": "Shows the trail of navigation taken to the current location.",
  "catalog.item.navigationview.title": "NavigationView",
  "catalog.item.navigationview.subtitle": "Common vertical layout for top-level areas of your app via a collapsible navigation menu.",
  "catalog.item.pivot.title": "Pivot",
  "catalog.item.pivot.subtitle": "Presents information from different sources in a tabbed view.",
  "catalog.item.selectorbar.title": "SelectorBar",
  "catalog.item.tabview.title": "TabView",
  "catalog.item.tabview.subtitle": "A control that displays a collection of tabs that can be used to display several documents.",
  "catalog.item.selectorbar.subtitle": "Presents information from a small set of different sources. The user can pick one of them.",
  "catalog.item.pipspager.title": "PipsPager",
  "catalog.item.pipspager.subtitle": "A control to let the user navigate through a paginated collection when the page numbers do not need to be visually known.",
  "catalog.item.scrollview.title": "ScrollView",
  "catalog.item.scrollview.subtitle": "A container control that lets the user pan and zoom its content.",
  "catalog.item.scrollviewer.title": "ScrollViewer",
  "catalog.item.scrollviewer.subtitle": "A container control that lets the user pan and zoom its content.",
  "catalog.item.semanticzoom.title": "SemanticZoom",
  "catalog.item.semanticzoom.subtitle": "Lets the user zoom between two different views of a collection, making it easier to navigate through large collections of items.",
  "catalog.item.infobadge.title": "InfoBadge",
  "catalog.item.infobadge.subtitle": "An non-intrusive UI to display notifications or bring focus to an area.",
  "catalog.item.infobar.title": "InfoBar",
  "catalog.item.infobar.subtitle": "An inline message to display app-wide status change information.",
  "catalog.item.progressbar.title": "ProgressBar",
  "catalog.item.progressbar.subtitle": "Shows the apps progress on a task, or that the app is performing ongoing work that doesn't block user interaction.",
  "catalog.item.progressring.title": "ProgressRing",
  "catalog.item.progressring.subtitle": "Shows the apps progress on a task, or that the app is performing ongoing work that does block user interaction.",
  "catalog.item.tooltip.title": "ToolTip",
  "catalog.item.tooltip.subtitle": "Displays information for an element in a pop-up window.",
  "catalog.item.acrylic.title": "AcrylicBrush",
  "catalog.item.acrylic.subtitle": "A translucent material recommended for panel backgrounds.",
  "catalog.item.animatedicon.title": "AnimatedIcon",
  "catalog.item.animatedicon.subtitle": "An element that displays and controls an icon that animates when the user interacts with the control.",
  "catalog.item.compactsizing.title": "Compact Sizing",
  "catalog.item.compactsizing.subtitle": "How to use a Resource Dictionary to enable compact sizing.",
  "catalog.item.iconelement.title": "IconElement",
  "catalog.item.iconelement.subtitle": "Represents icon controls that use different image types as its content.",
  "catalog.item.line.title": "Line",
  "catalog.item.line.subtitle": "Draws a straight line between two points.",
  "catalog.item.radialgradientbrush.title": "RadialGradientBrush",
  "catalog.item.radialgradientbrush.subtitle": "A brush to show radial gradients.",
  "catalog.item.systembackdrops.title": "System Backdrops (Mica/Acrylic)",
  "catalog.item.systembackdropelement.title": "SystemBackdropElement",
  "catalog.item.systembackdropelement.subtitle": "An element to host system backdrop materials.",
  "catalog.item.systembackdrops.subtitle": "System backdrops, like Mica and Acrylic, for app windows.",
  "catalog.item.themeshadow.title": "ThemeShadow",
  "catalog.item.themeshadow.subtitle": "Adds a depth-aware shadow to UI elements using system lighting.",
  "catalog.item.autosuggestbox.title": "AutoSuggestBox",
  "catalog.item.autosuggestbox.subtitle": "A control to provide suggestions as a user is typing.",
  "catalog.item.numberbox.title": "NumberBox",
  "catalog.item.numberbox.subtitle": "A text control used for numeric input and evaluation of algebraic equations.",
  "catalog.item.passwordbox.title": "PasswordBox",
  "catalog.item.passwordbox.subtitle": "A control for entering passwords.",
  "catalog.item.richeditbox.title": "RichEditBox",
  "catalog.item.richeditbox.subtitle": "A rich text editing control that supports formatted text, hyperlinks, and other rich content.",
  "catalog.item.richtextblock.title": "RichTextBlock",
  "catalog.item.richtextblock.subtitle": "A control that displays formatted text, hyperlinks, inline images, and other rich content.",
  "catalog.item.textblock.title": "TextBlock",
  "catalog.item.textblock.subtitle": "A lightweight control for displaying small amounts of text.",
  "catalog.item.textbox.title": "TextBox",
  "catalog.item.textbox.subtitle": "A single-line or multi-line plain text field."
};
