export default {
  'sample.systembackdrops.types-header': 'Backdrop types',
  'sample.systembackdrops.mica-header': 'MicaController',
  'sample.systembackdrops.acrylic-header': 'DesktopAcrylicController',
  'sample.systembackdrops.show-window': 'Show window',
  'sample.systembackdrops.types-intro': 'A window can use one of the following system backdrops:',
  'sample.systembackdrops.mica-name': '1. Mica',
  'sample.systembackdrops.mica-description': ' — An opaque material that samples the desktop wallpaper once to tint the window background. Best for main app windows.',
  'sample.systembackdrops.mica-alt-name': '2. Mica Alt',
  'sample.systembackdrops.mica-alt-description': ' — A variant of Mica with stronger tinting. Recommended for apps with a tabbed title bar.',
  'sample.systembackdrops.acrylic-name': '3. Desktop Acrylic (Base)',
  'sample.systembackdrops.acrylic-description': ' — A semi-transparent material that shows a blurred view of the content behind the window.',
  'sample.systembackdrops.acrylic-thin-name': '4. Desktop Acrylic (Thin)',
  'sample.systembackdrops.acrylic-thin-description': ' — A lighter variant of Desktop Acrylic with more transparency.',
  'sample.systembackdrops.comparison-title': 'Mica vs. Acrylic:',
  'sample.systembackdrops.comparison-description': ' Mica is opaque and renders the desktop wallpaper within the window background. Desktop Acrylic is semi-transparent and reveals a blurred view of what is behind the window in real-time. Mica is more performant because it captures the wallpaper only once, while Acrylic updates continuously.',
  'sample.systembackdrops.api-intro': 'There are three backdrop types in the API:',
  'sample.systembackdrops.api-system-name': '• SystemBackdrop',
  'sample.systembackdrops.api-system-description': ' — The base class of every backdrop type.',
  'sample.systembackdrops.api-mica-name': '• MicaBackdrop',
  'sample.systembackdrops.api-mica-description': ' — Applies the Mica material. Set the Kind property to switch between Base and Alt.',
  'sample.systembackdrops.api-acrylic-name': '• DesktopAcrylicBackdrop',
  'sample.systembackdrops.api-acrylic-description': ' — Applies the Desktop Acrylic material (Base type only).',
  'sample.systembackdrops.requirements': 'All Mica variants require Windows 11 build 22000 or later. In-app acrylic (AcrylicBrush) is a separate XAML brush used within UI elements, not a window backdrop.',
  'sample.systembackdrops.mica-controller-description': 'MicaController provides a customizable way to apply the Mica material. You can modify: FallbackColor, Kind, LuminosityOpacity, TintColor, and TintOpacity.',
  'sample.systembackdrops.mica-kinds-intro': 'There are 2 kinds of Mica:',
  'sample.systembackdrops.mica-base-name': '1. Base',
  'sample.systembackdrops.mica-base-description': ' — The default, lighter appearance.',
  'sample.systembackdrops.mica-controller-alt-name': '2. Alt',
  'sample.systembackdrops.mica-controller-alt-description': ' — A darker appearance with stronger tinting of the desktop wallpaper.',
  'sample.systembackdrops.acrylic-controller-description': 'DesktopAcrylicController provides a customizable way to apply the Desktop Acrylic material. It supports the same customization properties as MicaController.',
  'sample.systembackdrops.acrylic-kinds-intro': 'There are 2 kinds of Desktop Acrylic:',
  'sample.systembackdrops.acrylic-base-name': '1. Base',
  'sample.systembackdrops.acrylic-base-description': ' — The default, darker appearance with less transparency.',
  'sample.systembackdrops.acrylic-controller-thin-name': '2. Thin',
  'sample.systembackdrops.acrylic-controller-thin-description': ' — A lighter appearance with more transparency.',
  'sample.systembackdrops.acrylic-controller-note': 'Note: DesktopAcrylicBackdrop always uses the Base kind. To use the Thin kind, you must use DesktopAcrylicController directly.',
  'sample.systembackdrops.window-title': 'SystemBackdrop sample window',
  'sample.systembackdrops.current-backdrop': 'Current backdrop',
  'sample.systembackdrops.window-theme': 'Window theme',
  'sample.systembackdrops.backdrop.mica': 'Mica',
  'sample.systembackdrops.backdrop.mica-alt': 'Mica Alt',
  'sample.systembackdrops.backdrop.acrylic': 'Acrylic',
  'sample.systembackdrops.backdrop.acrylic-thin': 'Acrylic Thin',
  'sample.systembackdrops.backdrop.none': 'None',
  'sample.systembackdrops.theme.default': 'Use system setting',
  'sample.systembackdrops.theme.light': 'Light',
  'sample.systembackdrops.theme.dark': 'Dark',
  'sample.systembackdrops.window-opened': 'Window opened.',
  'sample.systembackdrops.popup-blocked': 'The browser blocked the sample window. Allow pop-ups for this site and try again.',
  'sample.systembackdrops.window-unavailable': 'A window host is not available.',
  'sample.systembackdrops.window-failed': 'The sample window could not be opened.',
  'sample.systembackdrops.window-recovery-failed': 'The desktop host could not reconnect to this sample window. Keep this window open and retry after the host is available.',
  'sample.systembackdrops.retry-connection': 'Retry connection',
  'sample.systembackdrops.native-unavailable': 'A regular browser cannot display system backdrops. View this sample in a desktop host that supports system backdrops.',
  'sample.systembackdrops.high-contrast': 'High contrast is enabled. The window uses the system fallback color.',
  'sample.systembackdrops.inactive': 'The window is inactive. The window uses the fallback color.',
  'sample.systembackdrops.transparency-disabled': 'Transparency is disabled. The window uses the fallback color.',
  'sample.systembackdrops.energy-saver': 'Energy saver is enabled. The window uses the fallback color.',
  'sample.systembackdrops.mica-trying-acrylic': 'Mica is not supported. Trying Acrylic. ',
  'sample.systembackdrops.mica-alt-trying-acrylic': 'Mica Alt is not supported. Trying Acrylic. ',
  'sample.systembackdrops.acrylic-base-default': 'Acrylic Base is not supported. Switching to default color.',
  'sample.systembackdrops.acrylic-thin-default': 'Acrylic Thin is not supported. Switching to default color.',
  'sample.systembackdrops.effect-unavailable': 'The requested backdrop is not supported. The window uses the fallback color.',
  'sample.systembackdrops.applied': 'Background changed to {backdrop}.',
  'sample.systembackdrops.closed': 'Window closed.',
  'sample.systembackdrops.operation-failed': 'The backdrop or theme could not be changed.'
};
