export default {
  "text.titlebar": "TitleBar",
  "sample.titlebar.customization-intro": "For full title bar customization without using the TitleBar control, see the ",
  "sample.titlebar.app-window-title-bar": "AppWindowTitleBar",
  "sample.titlebar.sample-suffix": " sample.",
  "sample.titlebar.configuration-header": "TitleBar configuration",
  "sample.titlebar.drag-header": "TitleBar drag regions",
  "sample.titlebar.end-to-end-header": "End to end TitleBar sample",
  "sample.titlebar.search": "Search...",
  "sample.titlebar.title-option": "Title",
  "sample.titlebar.subtitle-option": "Subtitle",
  "sample.titlebar.default-title": "WinUI Gallery",
  "sample.titlebar.default-subtitle": "Preview",
  "sample.titlebar.back-button-option": "IsBackButtonVisible",
  "sample.titlebar.pane-toggle-option": "IsPaneToggleButtonVisible",
  "sample.titlebar.drag-description": "Drag regions can only be observed on a real window. Click the button below to open a sample window where you can toggle TitleBar.IsDragRegion on a status badge and call RecomputeDragRegions() after dynamic content changes.",
  "sample.titlebar.end-to-end-description": "Click the button below to see an end to end sample of a TitleBar in a new window, binding some of its properties to the NavigationView and navigation frame.",
  "sample.titlebar.configuration-output": "Title: {title}\nSubtitle: {subtitle}\nBack button: {back}\nPane toggle: {pane}",
  "sample.titlebar.visible": "Visible",
  "sample.titlebar.collapsed": "Collapsed",
  "sample.titlebar.drag-window-title": "TitleBar drag regions sample",
  "sample.titlebar.end-window-title": "TitleBarWindow",
  "sample.titlebar.browser-host-unavailable": "The sample window is open. A regular browser does not support native window drag regions or system backdrops. Use a desktop host that supports these features.",
  "sample.titlebar.drag-title": "Drag regions",
  "sample.titlebar.drag-subtitle": "Try dragging the window",
  "sample.titlebar.status-badge": "Status",
  "sample.titlebar.custom-drag-title": "Custom drag regions",
  "sample.titlebar.drag-guidance": "Try dragging the window from different parts of the title bar. Interactive controls (like the search box) are automatically excluded from the drag region by the new default behavior in Windows App SDK 2.1.",
  "sample.titlebar.badge-heading": "Status badge: TitleBar.IsDragRegion",
  "sample.titlebar.badge-guidance": "Pick a value for the badge in the title bar.",
  "sample.titlebar.badge-unset": "Unset (framework decides — clickable, since Button is interactive)",
  "sample.titlebar.badge-true": "True (always draggable — overrides the framework default)",
  "sample.titlebar.badge-false": "False (always clickable)",
  "sample.titlebar.dynamic-heading": "Dynamic content",
  "sample.titlebar.dynamic-guidance": "When you add or remove elements in TitleBar.Content at runtime, call RecomputeDragRegions() to refresh.",
  "sample.titlebar.toggle-extra": "Toggle extra title bar button",
  "sample.titlebar.recompute": "RecomputeDragRegions()",
  "sample.titlebar.badge-clicked": "Status badge clicked",
  "sample.titlebar.extra": "Extra",
  "sample.titlebar.extra-added": "Added a Button to TitleBar.Content. Call RecomputeDragRegions() to refresh drag regions.",
  "sample.titlebar.extra-removed": "Removed the Button. Call RecomputeDragRegions() to refresh drag regions.",
  "sample.titlebar.recomputed": "RecomputeDragRegions() called.",
  "sample.titlebar.end-subtitle": "TitleBar sample",
  "sample.titlebar.menu-item": "Menu Item{index}",
  "sample.titlebar.sample-page": "Sample Page {index}",
  "sample.titlebar.page1-body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  "sample.titlebar.nav-output": "Page {index}, navigation history: {count}"
};
