// Default resource values from WinUI-Reference/controls/dev/TitleBar.
export const titleBarResources: Readonly<Record<string, unknown>> = Object.freeze({
  TitleBarCompactHeight: 32,
  TitleBarExpandedHeight: 48,
  TitleBarBackButtonWidth: 40,
  TitleBarPaneToggleButtonWidth: 40,
  TitleBarLeftPaddingWidth: 2,
  TitleBarRightPaddingWidth: 0,
  TitleBarLeftHeaderPaddingWidth: 14,
  TitleBarHeaderNegativeInsetPaddingWidth: 2,
  TitleBarMinDragRegionWidth: 48,
  TitleBarDeactivatedOpacity: 0.5,
  TitleBarCompactContentMargin: '0,0,16,0',
  TitleBarIconMaxWidth: 16,
  TitleBarIconMaxHeight: 16,
  TitleBarTitleMinWidth: 0,
  TitleBarSubtitleMinWidth: 0,
  TitleBarIconMargin: '0,0,16,0',
  TitleBarTitleMargin: '0,0,8,0',
  TitleBarSubtitleMargin: '0,0,16,0',
  TitleBarLeftHeaderHorizontalAlignment: 'Left',
  TitleBarLeftHeaderVerticalAlignment: 'Center',
  TitleBarContentHorizontalAlignment: 'Center',
  TitleBarContentVerticalAlignment: 'Center',
  TitleBarRightHeaderHorizontalAlignment: 'Right',
  TitleBarRightHeaderVerticalAlignment: 'Center',
})

export const titleBarBrushAliases: Readonly<Record<string, string>> = Object.freeze({
  TitleBarForegroundBrush: 'TextFillColorPrimaryBrush',
  TitleBarDeactivatedForegroundBrush: 'TextFillColorTertiaryBrush',
  TitleBarSubtitleForegroundBrush: 'TextFillColorSecondaryBrush',
  TitleBarSubtitleDeactivatedForegroundBrush: 'TextFillColorTertiaryBrush',
  TitleBarBackButtonBackground: 'SubtleFillColorTransparentBrush',
  TitleBarBackButtonBackgroundPointerOver: 'SubtleFillColorSecondaryBrush',
  TitleBarBackButtonBackgroundPressed: 'SubtleFillColorTertiaryBrush',
  TitleBarBackButtonBackgroundDisabled: 'ControlFillColorDisabledBrush',
  TitleBarBackButtonForeground: 'TextFillColorPrimaryBrush',
  TitleBarBackButtonForegroundPointerOver: 'TextFillColorPrimaryBrush',
  TitleBarBackButtonForegroundPressed: 'TextFillColorSecondaryBrush',
  TitleBarBackButtonForegroundDisabled: 'TextFillColorDisabledBrush',
  TitleBarPaneToggleButtonBackground: 'SubtleFillColorTransparentBrush',
  TitleBarPaneToggleButtonBackgroundPointerOver: 'SubtleFillColorSecondaryBrush',
  TitleBarPaneToggleButtonBackgroundPressed: 'SubtleFillColorTertiaryBrush',
  TitleBarPaneToggleButtonBackgroundDisabled: 'ControlFillColorDisabledBrush',
  TitleBarPaneToggleButtonForeground: 'TextFillColorPrimaryBrush',
  TitleBarPaneToggleButtonForegroundPointerOver: 'TextFillColorPrimaryBrush',
  TitleBarPaneToggleButtonForegroundPressed: 'TextFillColorSecondaryBrush',
  TitleBarPaneToggleButtonForegroundDisabled: 'TextFillColorDisabledBrush',
})

// HighContrast entries from TitleBar_themeresources.xaml. They deliberately
// use system control resources rather than the Light/Default text brushes.
export const titleBarHighContrastBrushAliases: Readonly<Record<string, string>> = Object.freeze({
  TitleBarForegroundBrush: 'SystemControlForegroundBaseHighBrush',
  TitleBarDeactivatedForegroundBrush: 'SystemControlDisabledBaseMediumLowBrush',
  TitleBarSubtitleForegroundBrush: 'SystemControlHighlightAltBaseHighBrush',
  TitleBarSubtitleDeactivatedForegroundBrush: 'SystemControlDisabledBaseMediumLowBrush',
  TitleBarBackButtonBackground: 'SystemControlBackgroundBaseLowBrush',
  TitleBarBackButtonBackgroundPointerOver: 'SystemControlHighlightListLowBrush',
  TitleBarBackButtonBackgroundPressed: 'SystemControlHighlightListMediumBrush',
  TitleBarBackButtonBackgroundDisabled: 'SystemControlBackgroundBaseLowBrush',
  TitleBarBackButtonForeground: 'SystemControlForegroundBaseHighBrush',
  TitleBarBackButtonForegroundPointerOver: 'SystemControlHighlightAltBaseHighBrush',
  TitleBarBackButtonForegroundPressed: 'SystemControlHighlightAltBaseHighBrush',
  TitleBarBackButtonForegroundDisabled: 'SystemControlDisabledBaseMediumLowBrush',
  TitleBarPaneToggleButtonBackground: 'SystemControlBackgroundBaseLowBrush',
  TitleBarPaneToggleButtonBackgroundPointerOver: 'SystemControlHighlightListLowBrush',
  TitleBarPaneToggleButtonBackgroundPressed: 'SystemControlHighlightListMediumBrush',
  TitleBarPaneToggleButtonBackgroundDisabled: 'SystemControlBackgroundBaseLowBrush',
  TitleBarPaneToggleButtonForeground: 'SystemControlForegroundBaseHighBrush',
  TitleBarPaneToggleButtonForegroundPointerOver: 'SystemControlHighlightAltBaseHighBrush',
  TitleBarPaneToggleButtonForegroundPressed: 'SystemControlHighlightAltBaseHighBrush',
  TitleBarPaneToggleButtonForegroundDisabled: 'SystemControlDisabledBaseMediumLowBrush',
})
